### PR TITLE
Position Based Elastic Rods 

### PR DESCRIPTION
**Pull request by korzen**
Hi Jan,

I have added an initial implementation of Position Based Elastic Rods paper by Umetani to your library.

elastirod

I hope that you will find it useful. I will work on it a bit more when time allows. Check ReadMe file in Demo/ElastiRodDemo folder for release notes

Here is .exe for a quick look:
https://github.com/korzen/PositionBasedDynamics-ElasticRod/releases/download/v0.1/PBD_ElasticRodDemo.zip

IMPORTANT: The OpenMP is not supported by the rod demo at the moment. I don't know CMake well, so maybe you could deactivate it for ElasticRodDemo target for now and I will look into how to parallelize the model. Thanks.

Best regards

Przemyslaw Korzeniowski

### CODE REVIEW

**Comment by janbender** [comment]
That is great :)
I will take a closer look at it after the Siggraph deadline. 

Jan

**Comment by janbender** [comment]
Hi, 

I just tested your elastic rod demo. It looks nice. However, when I use larger values for the Darboux vector, the model starts to oscillate and gains energy. I used the values:

time step size =0.005s
bend = 1
Darboux = (0.15, 0.55, 0.85)

Maybe you can have a look at this problem. Moreover, I have seen that another fork of your project fixed some possible divisions by zero. Maybe you could integrate this in your code. 

Jan

**Comment by mmmovania** [comment]
Hi Jan and korzen,
   I set your given initial values in my fork and the system remains stable after setting these values the system remains stable.

**Comment by korzen** [comment]
Hello,

the model with these settings seems OK. However, I admit that there are  
settings (e.g. high both X and Y rest Darbouxs) that are unstable and gain  
energy. I am not 100% sure yet if this is because some bugs in the code or  
simply the way the model works (floating point issues etc.). Nevertheless,  
this model is very stable comparing to other Cosserat rods (e.g. CoRdE by  
J. Spillmann).

I will be definitely using this model for my applications in medical VR  
simulation in the very near future. I will commit all the fixes and  
improvements.
First of all, the code using Eigen is nearly x10 (!) slower than the code  
I have nearly directly ported from (https://github.com/serpheroth/rod).

Why are you not using vectorized structures  (Vector4f and Matrix4f) in  
the library? I understand that the library is for educational purposes  
(which is great, thanks) but I don't think that switching from Vec3s to  
Vec4s would blur the code a lot.

I will pull the fixes from mobeen and I have got the OpenMP nearly fixed .

Here is the discussion  
http://bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=4&t=10993

Best regards

Przemyslaw


On Wed, 13 Jan 2016 08:44:45 +0100, Jan Bender <notifications@github.com>  
wrote:

>
> Hi,
> I just tested your elastic rod demo. It looks nice. However, when I use  
> larger values for the Darboux vector, the model starts to oscillate and  
> gains energy. >I used the values:
>
> time step size =0.005s
> bend = 1
> Darboux = (0.15, 0.55, 0.85)
>
> Maybe you can have a look at this problem. Moreover, I have seen that  
> another fork of your project fixed some possible divisions by zero.  
> Maybe you >could integrate this in your code.
> Jan
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Using Opera's mail client: http://www.opera.com/mail/

**Comment by janbender** [comment]
Hi, 

sorry that I didn't find the time yet to integrate your code. I will try to make it in the next weeks. However, before I have to adapt your code otherwise it won't work with the new version of PBD: 

Jan

**Comment by korzen** [comment]
Hello Jan,

no worries. I am very busy as well, but if I find some free evening before you I will adapt the code to your latest PBD version. I will let you know before that, not to double our work.

Meanwhile, keep on the good work with the PBD!

Best regards

Przemyslaw

**Comment by termi3** [comment]
Dear Jan an Przemyslaw
i tried to adjust both versions here  https://github.com/janbender/PositionBasedDynamics/pull/19
but have few linking errors. Probably some of you can solve these easier after that. Best regards  termi

**Comment by janbender** [comment]
I just integrated the position-based elastic rods code in the PBD library. I put an acknowledgement in the code and in a readme file in the demo folder. Hope that's okay for you. 

Thanks for the code. 

Jan

**Pull request closed without merging**
